### ISSUE TITLE
Cannot deploy code demo

### ISSUE THREAD

**Issue by dovuthanh** [Opus-foundation/contracts#1]
Hi Team,

1. I follow your instruction and getting issue when I run "npm run dev" 

npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/IOSDeveloper/.npm/_logs/2017-07-21T09_55_09_345Z-debug.log
iOSDeveloper:contracts IOSDeveloper$ 

2. But when I try with "npm run test" 

/Users/IOSDeveloper/Desktop/contracts/node_modules/truffle/lib/commands/test.js:39
      files = files.filter(function(file) {
                   ^
TypeError: Cannot read property 'filter' of undefined
    at /Users/IOSDeveloper/Desktop/contracts/node_modules/truffle/lib/commands/test.js:39:20
    at onStat (/Users/IOSDeveloper/Desktop/contracts/node_modules/node-dir/lib/paths.js:149:21)
    at FSReqWrap.oncomplete (fs.js:152:21)
3. Also "truffle migrate"
/Users/IOSDeveloper/Desktop/contracts/contracts/ERC23BasicToken.sol:20:28: : Unused local variable
    function tokenFallback(address _from, uint256 _value, bytes  _data) external {
                           ^-----------^
,/Users/IOSDeveloper/Desktop/contracts/contracts/ERC23BasicToken.sol:20:43: : Unused local variable
    function tokenFallback(address _from, uint256 _value, bytes  _data) external {
                                          ^------------^
,/Users/IOSDeveloper/Desktop/contracts/contracts/ERC23BasicToken.sol:20:59: : Unused local variable
    function tokenFallback(address _from, uint256 _value, bytes  _data) external {
                                                          ^----------^
,/Users/IOSDeveloper/Desktop/contracts/contracts/ERC23BasicToken.sol:72:25: : Unused local variable
    function isContract(address _addr) returns (bool is_contract) {
                        ^-----------^

Writing artifacts to ./build/contracts

Using network 'development'.

Error: Could not find built Migrations contract: Could not find artifacts for ./Migrations.sol from any sources
    at Object.lastCompletedMigration (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:54982:23)
    at Object.needsMigrating (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:55005:10)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:81657:19
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:46796:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:33762:13
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:224637:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:223413:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:225286:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:225576:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:225731:12)

I really interested in your project. Please give me some advice to get your demo project work on my machine.

Thanks,
Do

**Comment by chennyhaohao** [comment]
Hi,
We are looking into the building errors. Meanwhile, you can already try this demo at https://opus-foundation.org/advanced-demo.html
Thank you for your interest!

**Comment by dovuthanh** [comment]
Hi,

Do you have any updated?
Thanks,
Do

**Comment by AamirSuhial** [comment]
is there any fix for dev? in JSON package do we have to specify the dev.. as npm start dev doesnt not find DEV

**Comment by AamirSuhial** [comment]
SOLVED... -> JUST NEEDED TO UPDATE UPDATE TRUFFLE TO LATEST
NPM INSTALL -G TRUFFLE
AND UPDATE OTHER DEPENDENCIES AS WELL, AS THEY ARE QUITE OLD
